package web

// ErrorResponseJson is the struct used for sending failure error response in json format to the end user/client or
// frontend
type ErrorResponseJson struct {
	Error string
}

// Error struct is used by the core of our app to generate error messages that we want to send to end user
// This struct would be used to send trusted errors that are generated by us
type Error struct {
	err    error
	status int
}

// Error // implementing it over Error struct, so we can use errors.As functionality
func (err *Error) Error() string {
	return err.err.Error()
}

// NewRequestError would be called by other layers to generate user friend msg without disclosing internal details
func NewRequestError(err error, status int) error {
	return &Error{
		err:    err,
		status: status,
	}

}
